name: Build GH Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"
      - name: Build
        run: trunk build --release --public-url ${{ github.event.repository.name }}
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: dist
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
