name: Build GH Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: trunk build --release
